# Copyright 2022 Universidad Politécnica de Madrid
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
  annotations:
    prometheus.io/scrape: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:18.0.0
        resources: {}
        command: ["/bin/sh", "-c"]
        args:
          - echo starting;
            printenv;
            /opt/keycloak/bin/kc.sh build --db postgres;
            /opt/keycloak/bin/kc.sh show-config; 
            /opt/keycloak/bin/kc.sh -v start --db-url-database=keycloak --db-url-host=${KC_DB_URL} --db-username=${KC_DB_USERNAME} --db-password=${KC_DB_PASSWORD};
            #
        env:
        # Admin Configuration
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: adminpass
        # Database Configuration
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-helm-postgresql
              key: password
        - name: KC_DB_USERNAME
          value: "keycloak"
        - name: KC_DB_URL
          value: "jdbc:postgresql://keycloak-helm-postgresql/keycloak"
        - name: KC_DB_SCHEMA
          value: "public"
        # Hostname and reverse proxy configuration
        - name: KC_HTTP_RELATIVE_PATH
          value: "/auth"
        - name: KC_FRONTEND_URL
          value: "https://fosps.gravitatehealth.eu/auth"
        - name: KC_HOSTNAME
          value: "fosps.gravitatehealth.eu"
        - name: KC_HOSTNAME_STRICT
          value: "false"
        # Other configuration
        - name: KC_PROXY
          value: "edge"
        - name: KC_HTTP_ENABLED
          value: "true"
#        - name: KC_LOG_LEVEL
#          value: debug
####        - name: KC_DB_USERNAME
####          value: "keycloak"
####        - name: KC_DB_SCHEMA
####          value: "public"
####        - name: KC_DB_URL
####          value: "jdbc:postgresql://keycloak-helm-postgresql/keycloak"
####        # URL Configuration
####        - name: KC_HTTP_RELATIVE_PATH
####          value: "/auth"
####        #- name: KEYCLOAK_FRONTEND_URL
####        #  value: "https://fosps.gravitatehealth.eu/auth"
####        - name: KC_ADMIN_URL
####          value: "https://fosps.gravitatehealth.eu/auth/realms/master/admin/"
####        - name: "KC_PROXY_ADDRESS_FORWARDING"
####          value: "true"
####        #- name: KC_FEATURES_DISABLED
####        #  value: admin2
####        #- name: KC_FRONTEND_URL
####        #  value: "fosps.gravitatehealth.eu/auth"
####        #- name: KC_PROXY
####        #  value: "edge"
####        - name: KC_HOSTNAME_STRICT
####          value: "true"
#        - name: KC_HOSTNAME
#          value: "fosps.gravitatehealth.eu/auth"
####        - name: KC_HOSTNAME_ADMIN
####          value: "fosps.gravitatehealth.eu/auth"
####        #- name: KEYCLOAK_HOSTNAME
####          #value: "fosps.gravitatehealth.eu"
####        #- name: KC_HOSTNAME_URL
####        #  value: "fosps.gravitatehealth.eu/auth/"
####        #- name: KC_HOSTNAME_ADMIN_URL
####        #  value: "fosps.gravitatehealth.eu/auth/realms/master/admin/"
####        - name: KC_HTTP_ENABLED
####          value: "true"
####        #- name: KC_LOG_LEVEL
####        #  value: debug
        ports:
        - name: http
          containerPort: 8080